/*
 * Created on 2024-01-16 ( 16:42:22 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.pxil.sec.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;


/**
 * JPA entity class for "ApiRefreshToken"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="api_refresh_token" )
@JsonIgnoreProperties({"createdOn","createdBy","modifiedOn","modifiedBy","activeC"})

public class ApiRefreshToken implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="refresh_token", nullable=false, length=200)
    private String     refreshToken ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="expiry_date", nullable=false)
    private Date       expiryDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on")
    private Date       createdOn ;

    @Column(name="created_by")
    private Integer    createdBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_on")
    private Date       modifiedOn ;

    @Column(name="modified_by")
    private Integer    modifiedBy ;

    @Column(name="active_c", nullable=false, length=1)
    private String     activeC="Y" ;

    @Column(name="user_id")
    private Integer    userId ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="user_id", referencedColumnName="id", insertable=false, updatable=false)
    private ApiUser    apiUser ; 


    /**
     * Constructor
     */
    public ApiRefreshToken() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setRefreshToken( String refreshToken ) {
        this.refreshToken = refreshToken ;
    }
    public String getRefreshToken() {
        return this.refreshToken;
    }

    public void setExpirydate( Date expiryDate ) {
        this.expiryDate = expiryDate ;
    }
    public Date getExpirydate() {
        return this.expiryDate;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn ;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedBy( Integer createdBy ) {
        this.createdBy = createdBy ;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn ;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setModifiedBy( Integer modifiedBy ) {
        this.modifiedBy = modifiedBy ;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }

    public void setActiveC( String activeC ) {
        this.activeC = activeC ;
    }
    public String getActiveC() {
        return this.activeC;
    }

    public void setUserId( Integer userId ) {
        this.userId = userId ;
    }
    public Integer getUserId() {
        return this.userId;
    }

    //--- GETTERS FOR LINKS
    public ApiUser getApiUser() {
        return this.apiUser;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(refreshToken);
        sb.append("|");
        sb.append(expiryDate);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(activeC);
        sb.append("|");
        sb.append(userId);
        return sb.toString(); 
    } 

}
