/*
 * Created on 2023-12-05 ( 16:25:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.pxil.sec.entities;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * JPA entity class for "ApiUserGroup"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="api_user_group")
@JsonIgnoreProperties({"apiUser","apiGroup","createdOn","createdBy","modifiedOn","modifiedBy","activeC"})
public class ApiUserGroup implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="api_user_id", nullable=false)
    private Integer    apiUserId ;

    @Column(name="api_group_id", nullable=false)
    private Integer    apiGroupId ;

    @Temporal(TemporalType.DATE)
    @Column(name="created_on", nullable=false)
    private Date       createdOn ;

    @Column(name="created_by")
    private Integer    createdBy ;

    @Temporal(TemporalType.DATE)
    @Column(name="modified_on")
    private Date       modifiedOn ;

    @Column(name="modified_by")
    private Integer    modifiedBy ;

    @Column(name="active_c", nullable=false, length=1)
    private String     activeC ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne    
    @JoinColumn(name="api_user_id", referencedColumnName="id", insertable=false, updatable=false)
   // @JsonManagedReference
    private ApiUser    apiUser ; 

    @ManyToOne  
    @JoinColumn(name="api_group_id", referencedColumnName="id", insertable=false, updatable=false)
   // @JsonManagedReference
    private ApiGroup   apiGroup ; 


    /**
     * Constructor
     */
    public ApiUserGroup() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setApiUserId( Integer apiUserId ) {
        this.apiUserId = apiUserId ;
    }
    public Integer getApiUserId() {
        return this.apiUserId;
    }

    public void setApiGroupId( Integer apiGroupId ) {
        this.apiGroupId = apiGroupId ;
    }
    public Integer getApiGroupId() {
        return this.apiGroupId;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn ;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedBy( Integer createdBy ) {
        this.createdBy = createdBy ;
    }
    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn ;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setModifiedBy( Integer modifiedBy ) {
        this.modifiedBy = modifiedBy ;
    }
    public Integer getModifiedBy() {
        return this.modifiedBy;
    }

    public void setActiveC( String activeC ) {
        this.activeC = activeC ;
    }
    public String getActiveC() {
        return this.activeC;
    }

    //--- GETTERS FOR LINKS
    public ApiUser getApiUser() {
        return this.apiUser;
    } 

    public ApiGroup getApiGroup() {
        return this.apiGroup;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(apiUserId);
        sb.append("|");
        sb.append(apiGroupId);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(activeC);
        return sb.toString(); 
    } 

}
