/*
 * Created on 2024-01-10 ( 21:39:43 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.pxil.pvt.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "ApiScheduleWithLossCommaSeparated"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="api_schedule_with_loss_comma_separated" )
public class ApiScheduleWithLossCommaSeparated implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="product_code", length=15)
    private String     productCode ;

    @Column(name="product_type", length=5)
    private String     productType ;

    @Temporal(TemporalType.DATE)
    @Column(name="delivery_from_date")
    private Date       deliveryFromDate ;

    @Temporal(TemporalType.DATE)
    @Column(name="delivery_to_date")
    private Date       deliveryToDate ;

    @Column(name="unit_code", length=25)
    private String     unitCode ;

    @Column(name="unit_name", length=100)
    private String     unitName ;

    @Column(name="px_code", length=15)
    private String     pxCode ;

    @Column(name="side", length=1)
    private String     side ;

    @Column(name="power_source_type", length=12)
    private String     powerSourceType ;

    @Column(name="regional_entity", length=10)
    private String     regionalEntity ;

    @Column(name="grid_node_code", length=30)
    private String     gridNodeCode ;

    @Column(name="node_desc", length=100)
    private String     nodeDesc ;

    @Column(name="withoutloss", length=2147483647)
    private String     withoutloss ;

    @Column(name="regionalinjectionlossper", length=2147483647)
    private String     regionalinjectionlossper ;

    @Column(name="stateinjectionlossper", length=2147483647)
    private String     stateinjectionlossper ;

    @Column(name="regionalwithdrawallossper", length=2147483647)
    private String     regionalwithdrawallossper ;

    @Column(name="statewithdrawallossper", length=2147483647)
    private String     statewithdrawallossper ;

    @Column(name="withregionloss", length=2147483647)
    private String     withregionloss ;

    @Column(name="withsldcloss", length=2147483647)
    private String     withsldcloss ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on")
    private Date       createdOn ;

    @Column(name="created_by", length=25)
    private String     createdBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_on")
    private Date       modifiedOn ;

    @Column(name="modified_by", length=25)
    private String     modifiedBy ;

    @Column(name="active_c", length=1)
    private String     activeC ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public ApiScheduleWithLossCommaSeparated() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setProductCode( String productCode ) {
        this.productCode = productCode ;
    }
    public String getProductCode() {
        return this.productCode;
    }

    public void setProductType( String productType ) {
        this.productType = productType ;
    }
    public String getProductType() {
        return this.productType;
    }

    public void setDeliveryFromDate( Date deliveryFromDate ) {
        this.deliveryFromDate = deliveryFromDate ;
    }
    public Date getDeliveryFromDate() {
        return this.deliveryFromDate;
    }

    public void setDeliveryToDate( Date deliveryToDate ) {
        this.deliveryToDate = deliveryToDate ;
    }
    public Date getDeliveryToDate() {
        return this.deliveryToDate;
    }

    public void setUnitCode( String unitCode ) {
        this.unitCode = unitCode ;
    }
    public String getUnitCode() {
        return this.unitCode;
    }

    public void setUnitName( String unitName ) {
        this.unitName = unitName ;
    }
    public String getUnitName() {
        return this.unitName;
    }

    public void setPxCode( String pxCode ) {
        this.pxCode = pxCode ;
    }
    public String getPxCode() {
        return this.pxCode;
    }

    public void setSide( String side ) {
        this.side = side ;
    }
    public String getSide() {
        return this.side;
    }

    public void setPowerSourceType( String powerSourceType ) {
        this.powerSourceType = powerSourceType ;
    }
    public String getPowerSourceType() {
        return this.powerSourceType;
    }

    public void setRegionalEntity( String regionalEntity ) {
        this.regionalEntity = regionalEntity ;
    }
    public String getRegionalEntity() {
        return this.regionalEntity;
    }

    public void setGridNodeCode( String gridNodeCode ) {
        this.gridNodeCode = gridNodeCode ;
    }
    public String getGridNodeCode() {
        return this.gridNodeCode;
    }

    public void setNodeDesc( String nodeDesc ) {
        this.nodeDesc = nodeDesc ;
    }
    public String getNodeDesc() {
        return this.nodeDesc;
    }

    public void setWithoutloss( String withoutloss ) {
        this.withoutloss = withoutloss ;
    }
    public String getWithoutloss() {
        return this.withoutloss;
    }

    public void setRegionalinjectionlossper( String regionalinjectionlossper ) {
        this.regionalinjectionlossper = regionalinjectionlossper ;
    }
    public String getRegionalinjectionlossper() {
        return this.regionalinjectionlossper;
    }

    public void setStateinjectionlossper( String stateinjectionlossper ) {
        this.stateinjectionlossper = stateinjectionlossper ;
    }
    public String getStateinjectionlossper() {
        return this.stateinjectionlossper;
    }

    public void setRegionalwithdrawallossper( String regionalwithdrawallossper ) {
        this.regionalwithdrawallossper = regionalwithdrawallossper ;
    }
    public String getRegionalwithdrawallossper() {
        return this.regionalwithdrawallossper;
    }

    public void setStatewithdrawallossper( String statewithdrawallossper ) {
        this.statewithdrawallossper = statewithdrawallossper ;
    }
    public String getStatewithdrawallossper() {
        return this.statewithdrawallossper;
    }

    public void setWithregionloss( String withregionloss ) {
        this.withregionloss = withregionloss ;
    }
    public String getWithregionloss() {
        return this.withregionloss;
    }

    public void setWithsldcloss( String withsldcloss ) {
        this.withsldcloss = withsldcloss ;
    }
    public String getWithsldcloss() {
        return this.withsldcloss;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn ;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy ;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn ;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setModifiedBy( String modifiedBy ) {
        this.modifiedBy = modifiedBy ;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    public void setActiveC( String activeC ) {
        this.activeC = activeC ;
    }
    public String getActiveC() {
        return this.activeC;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(productCode);
        sb.append("|");
        sb.append(productType);
        sb.append("|");
        sb.append(deliveryFromDate);
        sb.append("|");
        sb.append(deliveryToDate);
        sb.append("|");
        sb.append(unitCode);
        sb.append("|");
        sb.append(unitName);
        sb.append("|");
        sb.append(pxCode);
        sb.append("|");
        sb.append(side);
        sb.append("|");
        sb.append(powerSourceType);
        sb.append("|");
        sb.append(regionalEntity);
        sb.append("|");
        sb.append(gridNodeCode);
        sb.append("|");
        sb.append(nodeDesc);
        sb.append("|");
        sb.append(withoutloss);
        sb.append("|");
        sb.append(regionalinjectionlossper);
        sb.append("|");
        sb.append(stateinjectionlossper);
        sb.append("|");
        sb.append(regionalwithdrawallossper);
        sb.append("|");
        sb.append(statewithdrawallossper);
        sb.append("|");
        sb.append(withregionloss);
        sb.append("|");
        sb.append(withsldcloss);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(activeC);
        return sb.toString(); 
    } 

}
