/*
 * Created on 2024-01-08 ( 16:39:12 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.pxil.pvt.entities;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

import com.pxil.sec.entities.PxGridNodeMstr;

/**
 * JPA entity class for "ApiScheduleWithLoss"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="api_schedule_with_loss")
public class ApiScheduleWithLoss implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="product_code", length=15)
    private String     productCode ;

    @Temporal(TemporalType.DATE)
    @Column(name="delivery_from_date")
    private Date       deliveryFromDate ;

    @Temporal(TemporalType.DATE)
    @Column(name="delivery_to_date")
    private Date       deliveryToDate ;

    @Column(name="from_slot_id")
    private BigDecimal fromSlotId ;

    @Column(name="to_slot_id")
    private BigDecimal toSlotId ;

    @Column(name="from_time", length=15)
    private String     fromTime ;

    @Column(name="to_time", length=15)
    private String     toTime ;

    @Column(name="tm_id", length=10)
    private String     tmId ;

    @Column(name="tm_name", length=100)
    private String     tmName ;

    @Column(name="tac_id", length=25)
    private String     tacId ;

    @Column(name="client_name", length=100)
    private String     clientName ;

    @Column(name="unit_code", length=25)
    private String     unitCode ;

    @Column(name="unit_name", length=25)
    private String     unitName ;

    @Column(name="px_code", length=15)
    private String     pxCode ;

    @Column(name="side", length=1)
    private String     side ;

    @Column(name="regional_entity", length=10)
    private String     regionalEntity ;

    @Column(name="node_desc", length=100)
    private String     nodeDesc ;

    @Column(name="connection_level")
    private BigDecimal connectionLevel ;

    @Column(name="grid_node_code", length=30)
    private String     gridNodeCode ;

    @Column(name="state_name", length=100)
    private String     stateName ;

    @Column(name="withoutloss")
    private BigDecimal withoutloss ;

    @Column(name="regionalinjectionlossper")
    private BigDecimal regionalinjectionlossper ;

    @Column(name="stateinjectionlossper")
    private BigDecimal stateinjectionlossper ;

    @Column(name="regionalwithdrawallossper")
    private BigDecimal regionalwithdrawallossper ;

    @Column(name="statewithdrawallossper")
    private BigDecimal statewithdrawallossper ;

    @Column(name="withregionloss")
    private BigDecimal withregionloss ;

    @Column(name="withsldcloss")
    private BigDecimal withsldcloss ;

    @Column(name="power_source_type", length=12)
    private String     powerSourceType ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on")
    private Date       createdOn ;

    @Column(name="created_by", length=25)
    private String     createdBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_on")
    private Date       modifiedOn ;

    @Column(name="modified_by", length=25)
    private String     modifiedBy ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToOne
    @JoinColumn(name="grid_node_code", referencedColumnName="gnm_grid_node_code", insertable=false, updatable=false)
    private PxGridNodeMstr pxGridNodeMstr ; 


    /**
     * Constructor
     */
    public ApiScheduleWithLoss() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setProductCode( String productCode ) {
        this.productCode = productCode ;
    }
    public String getProductCode() {
        return this.productCode;
    }

    public void setDeliveryFromDate( Date deliveryFromDate ) {
        this.deliveryFromDate = deliveryFromDate ;
    }
    public Date getDeliveryFromDate() {
        return this.deliveryFromDate;
    }

    public void setDeliveryToDate( Date deliveryToDate ) {
        this.deliveryToDate = deliveryToDate ;
    }
    public Date getDeliveryToDate() {
        return this.deliveryToDate;
    }

    public void setFromSlotId( BigDecimal fromSlotId ) {
        this.fromSlotId = fromSlotId ;
    }
    public BigDecimal getFromSlotId() {
        return this.fromSlotId;
    }

    public void setToSlotId( BigDecimal toSlotId ) {
        this.toSlotId = toSlotId ;
    }
    public BigDecimal getToSlotId() {
        return this.toSlotId;
    }

    public void setFromTime( String fromTime ) {
        this.fromTime = fromTime ;
    }
    public String getFromTime() {
        return this.fromTime;
    }

    public void setToTime( String toTime ) {
        this.toTime = toTime ;
    }
    public String getToTime() {
        return this.toTime;
    }

    public void setTmId( String tmId ) {
        this.tmId = tmId ;
    }
    public String getTmId() {
        return this.tmId;
    }

    public void setTmName( String tmName ) {
        this.tmName = tmName ;
    }
    public String getTmName() {
        return this.tmName;
    }

    public void setTacId( String tacId ) {
        this.tacId = tacId ;
    }
    public String getTacId() {
        return this.tacId;
    }

    public void setClientName( String clientName ) {
        this.clientName = clientName ;
    }
    public String getClientName() {
        return this.clientName;
    }

    public void setUnitCode( String unitCode ) {
        this.unitCode = unitCode ;
    }
    public String getUnitCode() {
        return this.unitCode;
    }

    public void setUnitName( String unitName ) {
        this.unitName = unitName ;
    }
    public String getUnitName() {
        return this.unitName;
    }

    public void setPxCode( String pxCode ) {
        this.pxCode = pxCode ;
    }
    public String getPxCode() {
        return this.pxCode;
    }

    public void setSide( String side ) {
        this.side = side ;
    }
    public String getSide() {
        return this.side;
    }

    public void setRegionalEntity( String regionalEntity ) {
        this.regionalEntity = regionalEntity ;
    }
    public String getRegionalEntity() {
        return this.regionalEntity;
    }

    public void setNodeDesc( String nodeDesc ) {
        this.nodeDesc = nodeDesc ;
    }
    public String getNodeDesc() {
        return this.nodeDesc;
    }

    public void setConnectionLevel( BigDecimal connectionLevel ) {
        this.connectionLevel = connectionLevel ;
    }
    public BigDecimal getConnectionLevel() {
        return this.connectionLevel;
    }

    public void setGridNodeCode( String gridNodeCode ) {
        this.gridNodeCode = gridNodeCode ;
    }
    public String getGridNodeCode() {
        return this.gridNodeCode;
    }

    public void setStateName( String stateName ) {
        this.stateName = stateName ;
    }
    public String getStateName() {
        return this.stateName;
    }

    public void setWithoutloss( BigDecimal withoutloss ) {
        this.withoutloss = withoutloss ;
    }
    public BigDecimal getWithoutloss() {
        return this.withoutloss;
    }

    public void setRegionalinjectionlossper( BigDecimal regionalinjectionlossper ) {
        this.regionalinjectionlossper = regionalinjectionlossper ;
    }
    public BigDecimal getRegionalinjectionlossper() {
        return this.regionalinjectionlossper;
    }

    public void setStateinjectionlossper( BigDecimal stateinjectionlossper ) {
        this.stateinjectionlossper = stateinjectionlossper ;
    }
    public BigDecimal getStateinjectionlossper() {
        return this.stateinjectionlossper;
    }

    public void setRegionalwithdrawallossper( BigDecimal regionalwithdrawallossper ) {
        this.regionalwithdrawallossper = regionalwithdrawallossper ;
    }
    public BigDecimal getRegionalwithdrawallossper() {
        return this.regionalwithdrawallossper;
    }

    public void setStatewithdrawallossper( BigDecimal statewithdrawallossper ) {
        this.statewithdrawallossper = statewithdrawallossper ;
    }
    public BigDecimal getStatewithdrawallossper() {
        return this.statewithdrawallossper;
    }

    public void setWithregionloss( BigDecimal withregionloss ) {
        this.withregionloss = withregionloss ;
    }
    public BigDecimal getWithregionloss() {
        return this.withregionloss;
    }

    public void setWithsldcloss( BigDecimal withsldcloss ) {
        this.withsldcloss = withsldcloss ;
    }
    public BigDecimal getWithsldcloss() {
        return this.withsldcloss;
    }

    public void setPowerSourceType( String powerSourceType ) {
        this.powerSourceType = powerSourceType ;
    }
    public String getPowerSourceType() {
        return this.powerSourceType;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn ;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy ;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn ;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setModifiedBy( String modifiedBy ) {
        this.modifiedBy = modifiedBy ;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    //--- GETTERS FOR LINKS
    public PxGridNodeMstr getPxGridNodeMstr() {
        return this.pxGridNodeMstr;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(productCode);
        sb.append("|");
        sb.append(deliveryFromDate);
        sb.append("|");
        sb.append(deliveryToDate);
        sb.append("|");
        sb.append(fromSlotId);
        sb.append("|");
        sb.append(toSlotId);
        sb.append("|");
        sb.append(fromTime);
        sb.append("|");
        sb.append(toTime);
        sb.append("|");
        sb.append(tmId);
        sb.append("|");
        sb.append(tmName);
        sb.append("|");
        sb.append(tacId);
        sb.append("|");
        sb.append(clientName);
        sb.append("|");
        sb.append(unitCode);
        sb.append("|");
        sb.append(unitName);
        sb.append("|");
        sb.append(pxCode);
        sb.append("|");
        sb.append(side);
        sb.append("|");
        sb.append(regionalEntity);
        sb.append("|");
        sb.append(nodeDesc);
        sb.append("|");
        sb.append(connectionLevel);
        sb.append("|");
        sb.append(gridNodeCode);
        sb.append("|");
        sb.append(stateName);
        sb.append("|");
        sb.append(withoutloss);
        sb.append("|");
        sb.append(regionalinjectionlossper);
        sb.append("|");
        sb.append(stateinjectionlossper);
        sb.append("|");
        sb.append(regionalwithdrawallossper);
        sb.append("|");
        sb.append(statewithdrawallossper);
        sb.append("|");
        sb.append(withregionloss);
        sb.append("|");
        sb.append(withsldcloss);
        sb.append("|");
        sb.append(powerSourceType);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(modifiedBy);
        return sb.toString(); 
    } 

}
