/*
 * Created on 2023-12-12 ( 15:30:47 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.pxil.pvt.entities;

import java.io.Serializable;
import java.util.Comparator;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "PxCeaAcpCommaSeparated"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="px_cea_acp_comma_separated" )
public class PxCeaAcpCommaSeparated implements Serializable,Comparator<PxCeaAcpCommaSeparated> {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="product", length=50)
    private String     product ;

    @Temporal(TemporalType.DATE)
    @Column(name="date")
    private Date       date ;

    @Column(name="region_code", length=50)
    private String     regionCode ;

    @Column(name="mcp", length=2147483647)
    private String     mcp ;

    @Column(name="report_name", length=2147483647)
    private String     reportName ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on")
    private Date       createdOn ;

    @Column(name="created_by", length=50)
    private String     createdBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_on")
    private Date       modifiedOn ;

    @Column(name="modified_by", length=50)
    private String     modifiedBy ;

    @Column(name="active_c", length=1)
    private String     activeC ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public PxCeaAcpCommaSeparated() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setProduct( String product ) {
        this.product = product ;
    }
    public String getProduct() {
        return this.product;
    }

    public void setDate( Date date ) {
        this.date = date ;
    }
    public Date getDate() {
        return this.date;
    }

    public void setRegionCode( String regionCode ) {
        this.regionCode = regionCode ;
    }
    public String getRegionCode() {
        return this.regionCode;
    }

    public void setMcp( String mcp ) {
        this.mcp = mcp ;
    }
    public String getMcp() {
        return this.mcp;
    }

    public void setReportName( String reportName ) {
        this.reportName = reportName ;
    }
    public String getReportName() {
        return this.reportName;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn ;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy ;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn ;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setModifiedBy( String modifiedBy ) {
        this.modifiedBy = modifiedBy ;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    public void setActiveC( String activeC ) {
        this.activeC = activeC ;
    }
    public String getActiveC() {
        return this.activeC;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(product);
        sb.append("|");
        sb.append(date);
        sb.append("|");
        sb.append(regionCode);
        sb.append("|");
        sb.append(mcp);
        sb.append("|");
        sb.append(reportName);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(activeC);
        return sb.toString(); 
    }

	@Override
	public int compare(PxCeaAcpCommaSeparated o1, PxCeaAcpCommaSeparated o2) {
		 return Long.valueOf(o1.getDate().getTime())
	                .compareTo(o2.getDate().getTime());
	}
}
