/*
 * Created on 2023-12-11 ( 16:18:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.pxil.pvt.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

/**
 * JPA entity class for "PxCeaDataCommaSeparated"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="px_cea_data_comma_separated" )
public class PxCeaDataCommaSeparated implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="product", length=50)
    private String     product ;

    @Temporal(TemporalType.DATE)
    @Column(name="date")
    private Date       date ;

    @Column(name="purchase_bid", length=2147483647)
    private String     purchaseBid ;

    @Column(name="sell_bid", length=2147483647)
    private String     sellBid ;

    @Column(name="mcv", length=2147483647)
    private String     mcv ;

    @Column(name="mcp", length=2147483647)
    private String     mcp ;

    @Column(name="congestion", length=2147483647)
    private String     congestion ;

    @Column(name="cleared_volume", length=2147483647)
    private String     clearedVolume ;

    @Column(name="real_time_curtailment", length=2147483647)
    private String     realTimeCurtailment ;

    @Column(name="final_scheduled_volume", length=2147483647)
    private String     finalScheduledVolume ;

    @Column(name="cleared_volume_solar", length=2147483647)
    private String     clearedVolumeSolar ;

    @Column(name="cleared_volume_non_solar", length=2147483647)
    private String     clearedVolumeNonSolar ;

    @Column(name="cleared_volume_hydro", length=2147483647)
    private String     clearedVolumeHydro ;

    @Column(name="final_scheduled_volume_solar", length=2147483647)
    private String     finalScheduledVolumeSolar ;

    @Column(name="final_scheduled_volume_nonsolar", length=2147483647)
    private String     finalScheduledVolumeNonsolar ;

    @Column(name="final_scheduled_volume_hydro", length=2147483647)
    private String     finalScheduledVolumeHydro ;

    @Column(name="report_name", length=2147483647)
    private String     reportName ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on")
    private Date       createdOn ;

    @Column(name="created_by", length=50)
    private String     createdBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modified_on")
    private Date       modifiedOn ;

    @Column(name="modified_by", length=50)
    private String     modifiedBy ;

    @Column(name="active_c", length=1)
    private String     activeC ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public PxCeaDataCommaSeparated() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setProduct( String product ) {
        this.product = product ;
    }
    public String getProduct() {
        return this.product;
    }

    public void setDate( Date date ) {
        this.date = date ;
    }
    public Date getDate() {
        return this.date;
    }

    public void setPurchaseBid( String purchaseBid ) {
        this.purchaseBid = purchaseBid ;
    }
    public String getPurchaseBid() {
        return this.purchaseBid;
    }

    public void setSellBid( String sellBid ) {
        this.sellBid = sellBid ;
    }
    public String getSellBid() {
        return this.sellBid;
    }

    public void setMcv( String mcv ) {
        this.mcv = mcv ;
    }
    public String getMcv() {
        return this.mcv;
    }

    public void setMcp( String mcp ) {
        this.mcp = mcp ;
    }
    public String getMcp() {
        return this.mcp;
    }

    public void setCongestion( String congestion ) {
        this.congestion = congestion ;
    }
    public String getCongestion() {
        return this.congestion;
    }

    public void setClearedVolume( String clearedVolume ) {
        this.clearedVolume = clearedVolume ;
    }
    public String getClearedVolume() {
        return this.clearedVolume;
    }

    public void setRealTimeCurtailment( String realTimeCurtailment ) {
        this.realTimeCurtailment = realTimeCurtailment ;
    }
    public String getRealTimeCurtailment() {
        return this.realTimeCurtailment;
    }

    public void setFinalScheduledVolume( String finalScheduledVolume ) {
        this.finalScheduledVolume = finalScheduledVolume ;
    }
    public String getFinalScheduledVolume() {
        return this.finalScheduledVolume;
    }

    public void setClearedVolumeSolar( String clearedVolumeSolar ) {
        this.clearedVolumeSolar = clearedVolumeSolar ;
    }
    public String getClearedVolumeSolar() {
        return this.clearedVolumeSolar;
    }

    public void setClearedVolumeNonSolar( String clearedVolumeNonSolar ) {
        this.clearedVolumeNonSolar = clearedVolumeNonSolar ;
    }
    public String getClearedVolumeNonSolar() {
        return this.clearedVolumeNonSolar;
    }

    public void setClearedVolumeHydro( String clearedVolumeHydro ) {
        this.clearedVolumeHydro = clearedVolumeHydro ;
    }
    public String getClearedVolumeHydro() {
        return this.clearedVolumeHydro;
    }

    public void setFinalScheduledVolumeSolar( String finalScheduledVolumeSolar ) {
        this.finalScheduledVolumeSolar = finalScheduledVolumeSolar ;
    }
    public String getFinalScheduledVolumeSolar() {
        return this.finalScheduledVolumeSolar;
    }

    public void setFinalScheduledVolumeNonsolar( String finalScheduledVolumeNonsolar ) {
        this.finalScheduledVolumeNonsolar = finalScheduledVolumeNonsolar ;
    }
    public String getFinalScheduledVolumeNonsolar() {
        return this.finalScheduledVolumeNonsolar;
    }

    public void setFinalScheduledVolumeHydro( String finalScheduledVolumeHydro ) {
        this.finalScheduledVolumeHydro = finalScheduledVolumeHydro ;
    }
    public String getFinalScheduledVolumeHydro() {
        return this.finalScheduledVolumeHydro;
    }

    public void setReportName( String reportName ) {
        this.reportName = reportName ;
    }
    public String getReportName() {
        return this.reportName;
    }

    public void setCreatedOn( Date createdOn ) {
        this.createdOn = createdOn ;
    }
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedBy( String createdBy ) {
        this.createdBy = createdBy ;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setModifiedOn( Date modifiedOn ) {
        this.modifiedOn = modifiedOn ;
    }
    public Date getModifiedOn() {
        return this.modifiedOn;
    }

    public void setModifiedBy( String modifiedBy ) {
        this.modifiedBy = modifiedBy ;
    }
    public String getModifiedBy() {
        return this.modifiedBy;
    }

    public void setActiveC( String activeC ) {
        this.activeC = activeC ;
    }
    public String getActiveC() {
        return this.activeC;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(product);
        sb.append("|");
        sb.append(date);
        sb.append("|");
        sb.append(purchaseBid);
        sb.append("|");
        sb.append(sellBid);
        sb.append("|");
        sb.append(mcv);
        sb.append("|");
        sb.append(mcp);
        sb.append("|");
        sb.append(congestion);
        sb.append("|");
        sb.append(clearedVolume);
        sb.append("|");
        sb.append(realTimeCurtailment);
        sb.append("|");
        sb.append(finalScheduledVolume);
        sb.append("|");
        sb.append(clearedVolumeSolar);
        sb.append("|");
        sb.append(clearedVolumeNonSolar);
        sb.append("|");
        sb.append(clearedVolumeHydro);
        sb.append("|");
        sb.append(finalScheduledVolumeSolar);
        sb.append("|");
        sb.append(finalScheduledVolumeNonsolar);
        sb.append("|");
        sb.append(finalScheduledVolumeHydro);
        sb.append("|");
        sb.append(reportName);
        sb.append("|");
        sb.append(createdOn);
        sb.append("|");
        sb.append(createdBy);
        sb.append("|");
        sb.append(modifiedOn);
        sb.append("|");
        sb.append(modifiedBy);
        sb.append("|");
        sb.append(activeC);
        return sb.toString(); 
    } 

}
